Updated DataCube.c to add creation of minor axis PV image
SoFiA-Admin/SoFiA-2 pull request #90
Opened 2022-10-24 14:44 UTC by vdhulst

added creation of minor axis PV diagram to DataCube.c

2022-10-26 01:57 UTC, SoFiA-Admin requested changes
Thank you, @vdhulst, for implementing the generation of PV diagrams along the minor axis. Overall, the code looks like it should work correctly. I added two separate comments to the code to suggest two minor changes before the new code can be merged into the SoFiA master branch.

2022-10-26 01:57 UTC, SoFiA-Admin commented on src/DataCube.c
> +		DataCube *pv_min = DataCube_create_pv(cubelet, Source_get_par_by_name_flt(src, "x") - x_min, Source_get_par_by_name_flt(src, "y") - y_min, Source_get_par_by_name_flt(src, "kin_pa") * M_PI / 180.0 +
Instead of using the somewhat unwieldy floating-point literal of 1.5707963268, I suggest to use the expression
```
(Source_get_par_by_name_flt(src, "kin_pa") + 90.0) * M_PI / 180.0
```
instead, as the value of `90.0` is exact and hence does not introduce arbitrary rounding errors apart from the ones naturally imposed by the limited dynamic range of double-precision floating-point arithmetic.

2022-10-26 01:57 UTC, SoFiA-Admin commented on src/DataCube.c
> +		DataCube *pv_min = DataCube_create_pv(cubelet, Source_get_par_by_name_flt(src, "x") - x_min, Source_get_par_by_name_flt(src, "y") - y_min, Source_get_par_by_name_flt(src, "kin_pa") * M_PI / 180.0 +
Another problem with this line is that it currently creates a memory leak, as a new object `pv_min` of class `DataCube` is created, but not deleted again after saving to disk. I suggest to add the following code after line 5777 further down:
```
DataCube_delete(pv_min);
```
This will call the destructor on the `pv_min` object and release all memory occupied by that object.

Unlike Python, C does not have implicit automatic garbage collection, and hence every object created in C must be explicitly deleted again after use, as otherwise it would persist in memory until execution of the programme ends.

2022-10-27 21:54 UTC, vdhulst commented on src/DataCube.c
> +		DataCube *pv_min = DataCube_create_pv(cubelet, Source_get_par_by_name_flt(src, "x") - x_min, Source_get_par_by_name_flt(src, "y") - y_min, Source_get_par_by_name_flt(src, "kin_pa") * M_PI / 180.0 +
Yes, I overlooked this. Thanks, added a line to release pv_min.

2022-10-27 21:54 UTC, vdhulst commented on src/DataCube.c
> +		DataCube *pv_min = DataCube_create_pv(cubelet, Source_get_par_by_name_flt(src, "x") - x_min, Source_get_par_by_name_flt(src, "y") - y_min, Source_get_par_by_name_flt(src, "kin_pa") * M_PI / 180.0 +
Done, this is indeed more appropriate

2022-11-07 06:45 UTC, SoFiA-Admin approved these changes

2022-11-07 06:46 UTC, merged

2022-11-07 07:52 UTC, paoloserra commented
working great for me!